# Generated by Django 4.1.7 on 2023-03-25 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='qty',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
